all: Main.class Flight.class Transaction.class Passenger.class
	java Main

Main.class: Main.java
	javac Main.java

Flight.class: Flight.java
	javac Flight.java

Passenger.class: Passenger.java
	javac Passenger.java

clean:
	rm Flight.class
	rm Passenger.class
	rm Main.class
	rm Transaction.class
