all: Node.class InternalNode.class LeafNode.class BPlusTree.class Data.class Test.class
	java Test
Node.class: Node.java
	javac Node.java

InternalNode.class: InternalNode.java
	javac InternalNode.java

LeafNode.class: LeafNode.java
	javac LeafNode.java

BPlusTree: BPlusTree.java
	javac BPlusTree.java

Data.class: Data.java
	javac Data.java

Test.class: Test.java
	javac Test.java

clean:
	rm Node.class
	rm InternalNode.class
	rm LeafNode.class
	rm BPlusTree.class
	rm Test.class