all: program1_2016123_2016048.class Flight.class Transaction.class Passenger.class
	java program1_2016123_2016048

program1_2016123_2016048.class: program1_2016123_2016048.java
	javac program1_2016123_2016048.java

Flight.class: Flight.java
	javac Flight.java

Passenger.class: Passenger.java
	javac Passenger.java

clean:
	rm Flight.class
	rm Passenger.class
	rm program1_2016123_2016048.class
	rm Transaction.class
